### ISSUE TITLE
Make note linking case-insensitive

### ISSUE THREAD

**Issue by HR-Guy** [AlexW00/obsidian-note-linker#19]
**Is your feature request related to a problem? Please describe.**
Imported notes that need linking all begin with capital letters.

**Describe the solution you'd like**
Plugin should link to notes without being case sensitive

**Describe alternatives you've considered**
Could rename all notes to be the required case but that would be an unimaginable amount of work.

**Comment by LessRinn** [comment]
yes please

**Comment by GoulartNogueira** [comment]
**+1 for this feature**
I believe this should be very simple.

Maybe as simple as setting the regex to case insensitive. Probably somewhere here:
https://github.com/AlexW00/obsidian-note-linker/tree/master/src/rs/matching
