### ISSUE TITLE
[ISSUE] Plugin wants to link wrong and redundant stuff

### ISSUE THREAD

**Issue by firinael** [AlexW00/obsidian-note-linker#2]
![image](https://user-images.githubusercontent.com/67032657/188054833-a35e598c-d716-4192-a763-f214dab9c4fd.png)

As you can see, the plugin wants to link things inside links, and wants to link notes to themselves. "Conjunto" written in the "conjunto.md" note would link to itself, as an example. Block references also are being recognized and linked to their own notes (breaking the references).

**Comment by AlexW00** [comment]
Thank you for the report. Cleaning up the contents of a note to remove "unwanted" parts of the note, which should not be replaced by links, indeed needs some extra changes. Currently, only code blocks and existing internal links are being ignored, the relevant code can be found in [IgnoreRange](https://github.com/AlexW00/obsidian-note-linker/blob/996b514a72d70ed2e73fd3cea80ef3d02a018c54/src/ts/objects/IgnoreRange.ts#L15). 

Anything other that has to be ignored, should be added to that part of the code, maybe even by adding the content of the note to the parameter of the function and doing some manual regex searches to identify unwanted parts of the note that are not tracked with the cache.

**Comment by AlexW00** [comment]
Implemented in 758916ace391c292a7f61b8bc3fefc51644361d7. Note Linker now ignores more things, such as:
- Block references
- HTML code
- MD links
- web links (without md syntax)

This feature will be part of the upcoming 0.1.1 update.
