### ISSUE TITLE
Note Linker uses a lot of resources and crashes my pc.

### ISSUE THREAD

**Issue by Txindoki666** [AlexW00/obsidian-note-linker#38]
Greetings, happy new year and thank you very much for the plugin. It is very useful for me. 
I wanted to note that the plugin has a strange behavior in my Obsidian.
I have 400 or so notes and when the plugin displays the final listing of the notes, I go note by note seeing which ones I link and which ones I don't. 
Every time I mark a note to link the resource usage goes way up (1,500 mb ram and 90% cpu) according to Windows 10 task manager). My pc gets slow for a few seconds. I have to wait about 30 to 40 seconds for the note to be marked for linking. That happens every time I click on a note to link it, so the whole process is very slow. Sometimes it even goes way up and Obsidian closes itself.
I have 16gb ram (2,400mhz) an intel i5 4460 processor, 320 Ghz. Notes and obsidian are installed on a NVMe samsung 970 evo plus. The rest of obsidian runs very smooth and only happens to me with this plugin.
Thanks again.

**Comment by VillalobosCristian** [comment]
Same problem for large vault :(

**Comment by AlexW00** [comment]
Hi. Please check out version 1.2.4, which added pagination.
