### ISSUE TITLE
Super slow for large vault

### ISSUE THREAD

**Issue by eriklgamedev** [AlexW00/obsidian-note-linker#43]
I have around 800 notes in my vault. 
The preview loads, but when you click the check to add the link, it just freezes for a long time for each link. I'm running on a very high-end PC. Please add the option to select and add all links with one click, currently, it's gonna take forever to add links for large vaults. Also as some people have mentioned, maybe add integration with ChatGPT? Maybe build on top of the Smart-Link Plugin to do that, ChatGPT is very good at finding links, it just doesn't have the function to link them.

**Comment by AlexW00** [comment]
Hi. Please check out version 1.2.4, which added pagination.
